version: '3.8'

services:
  db:
    image: postgres:15.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: intelliSpace
    volumes:
      - ./postgres:/var/lib/postgresql/data